# This Dockerfile is only useful for Goreleaser task
# https://goreleaser.com/customization/docker/
FROM cgr.dev/chainguard/static:latest
COPY tx-indexer /
WORKDIR /var/lib/app
ENTRYPOINT [ "/tx-indexer" ]
CMD [ "start" ]