package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"

	"github.com/gnolang/tx-indexer/serve/graph/model"
)

// ResponseData is the resolver for the response_data field.
func (r *transactionResolver) ResponseData(ctx context.Context, obj *model.Transaction) (string, error) {
	return string(obj.ResponseData()), nil
}

// Transaction returns TransactionResolver implementation.
func (r *Resolver) Transaction() TransactionResolver { return &transactionResolver{r} }

type transactionResolver struct{ *Resolver }
