query getAllRegisteredUsers {
  getTransactions(
    where: {messages: {value: {MsgCall: {func: {eq: "Register"}, pkg_path: {eq: "gno.land/r/demo/users"}}}}}
  ) {
    messages {
      value {
        ... on MsgCall {
          caller
          args
        }
      }
    }
  }
}