on:
  workflow_call:
    inputs:
      go-version:
        required: true
        type: string

jobs:
  generated-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go-version }}
      - name: Check generated files are up to date
        run: |
          go build -o bin/app .
