name: dev gnoswap push gnoswap-tx-indexer v2

on:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
jobs:
  dev_gnoswap_tx_indexer:
    name: Run tx-indexer app
    uses: ./.github/workflows/app_template.yml
    with:
      app-name: "tx-indexer"
      env: "dev-gnoswap-v2"
      helm-chart-repo: "gnoswap-labs/gnoswap-helm-chart"
    secrets:
      AWS_IAM_OIDC: ${{ secrets.AWS_IAM_OIDC }}
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      REGION: ${{ secrets.DEV_REGION_V2 }}
