on:
  workflow_call:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.x

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Lint
        uses: golangci/golangci-lint-action@v8
        with:
          args:
            --config=./.github/golangci.yaml
          version: v2.2
