on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Go Linter
    uses: ./.github/workflows/lint.yaml

  test:
    name: Go Test
    uses: ./.github/workflows/test.yaml

  codegen:
    name: Go Codegen
    uses: ./.github/workflows/gen.yaml
  
  grapqlcheck:
    name: GraphQL Check
    uses: ./.github/workflows/gqlCheck.yaml
